# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e41d71a41e1b757d5cf129479e6bf357e478317633cc1e5aa800672c9cfd78701661530788eec62abdf7ec28dbdf74bce70f9a4a95e941f0f1037a0695070b7

test:
  secret_key_base: 505fa1e07ea4e7026929d3755986dd7306e8d3b12456bd51c7fa635c6935159adfbe4ee5c025c037b428b1cd87fb2bb9ec7364c46ff08fe7a30ce7b7ed6af8e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
